language: python

install:
  - pip install poetry
  - poetry install

jobs:
  include:
    - stage: black
      script: poetry run black --check $(pwd)
      python: "3.6"
    - stage: mypy
      script: poetry run mypy $(pwd)/lunavl
      python: "3.8"
    - stage: bandit
      script: poetry run bandit -r $(pwd)
      python: "3.8"

